### ISSUE TITLE
Protect /counter API endpoint (for POST and GET requests)

### ISSUE THREAD

**Issue by ErnestUrzua** [mattlevan/toro-net#4]
# To-dos
- [ ] Implement persistent sessions (`sessions` collection in the database) so that application reboot does not destroy sessions
- [ ] Ensure synchronization between database sessions and local storage (cookies)
- [ ] Get `req.isAuthenticated()` to work properly (passportjs)

**Comment by ErnestUrzua** [comment]
I will focus on this for the weekend.

**Comment by hugoLucas** [comment]
This might be helpful to anyone trying to close this issue: 
https://scotch.io/tutorials/authenticate-a-node-js-api-with-json-web-tokens

**Comment by mattlevan** [comment]
JWT might be the way to go (or OAuth2 tokens since we might be able to pull them in from GitHub users already) for this. Check out these two recent blog tutorials for more info:

http://blog.slatepeak.com/refactoring-a-basic-authenticated-api-with-node-express-and-mongo/
https://jonathanmh.com/express-passport-json-web-token-jwt-authentication-beginners/
